// This file is auto-generated by @hey-api/openapi-ts

import { type Options, HealthService, LoginService, UsersService } from '../sdk.gen';
import { queryOptions, type UseMutationOptions, type DefaultError } from '@tanstack/react-query';
import type { GetHealthData, LoginData, LoginError, LoginResponse, RefreshData, RefreshError, RefreshResponse, LogoutData, LogoutError, LogoutResponse, RecoverPasswordData, RecoverPasswordError, RecoverPasswordResponse, ResetPasswordData, ResetPasswordError, ResetPasswordResponse, GetUsersData, CreateUserData, CreateUserError, CreateUserResponse, RegisterUserData, RegisterUserError, RegisterUserResponse, DeleteUserMeData, DeleteUserMeResponse, GetUserMeData, UpdateUserMeData, UpdateUserMeError, UpdateUserMeResponse, UpdatePasswordMeData, UpdatePasswordMeError, UpdatePasswordMeResponse, DeleteUserByIdData, DeleteUserByIdError, DeleteUserByIdResponse, GetUserByIdData, UpdateUserByIdData, UpdateUserByIdError, UpdateUserByIdResponse } from '../types.gen';
import type { AxiosError } from 'axios';
import { client as _heyApiClient } from '../client.gen';

export type QueryKey<TOptions extends Options> = [
    Pick<TOptions, 'baseURL' | 'body' | 'headers' | 'path' | 'query'> & {
        _id: string;
        _infinite?: boolean;
    }
];

const createQueryKey = <TOptions extends Options>(id: string, options?: TOptions, infinite?: boolean): [
    QueryKey<TOptions>[0]
] => {
    const params: QueryKey<TOptions>[0] = { _id: id, baseURL: (options?.client ?? _heyApiClient).getConfig().baseURL } as QueryKey<TOptions>[0];
    if (infinite) {
        params._infinite = infinite;
    }
    if (options?.body) {
        params.body = options.body;
    }
    if (options?.headers) {
        params.headers = options.headers;
    }
    if (options?.path) {
        params.path = options.path;
    }
    if (options?.query) {
        params.query = options.query;
    }
    return [
        params
    ];
};

export const getHealthQueryKey = (options?: Options<GetHealthData>) => createQueryKey('getHealth', options);

export const getHealthOptions = (options?: Options<GetHealthData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await HealthService.getHealth({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getHealthQueryKey(options)
    });
};

export const loginQueryKey = (options: Options<LoginData>) => createQueryKey('login', options);

export const loginOptions = (options: Options<LoginData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await LoginService.login({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: loginQueryKey(options)
    });
};

export const loginMutation = (options?: Partial<Options<LoginData>>) => {
    const mutationOptions: UseMutationOptions<LoginResponse, AxiosError<LoginError>, Options<LoginData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await LoginService.login({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const refreshQueryKey = (options: Options<RefreshData>) => createQueryKey('refresh', options);

export const refreshOptions = (options: Options<RefreshData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await LoginService.refresh({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: refreshQueryKey(options)
    });
};

export const refreshMutation = (options?: Partial<Options<RefreshData>>) => {
    const mutationOptions: UseMutationOptions<RefreshResponse, AxiosError<RefreshError>, Options<RefreshData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await LoginService.refresh({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const logoutQueryKey = (options: Options<LogoutData>) => createQueryKey('logout', options);

export const logoutOptions = (options: Options<LogoutData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await LoginService.logout({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: logoutQueryKey(options)
    });
};

export const logoutMutation = (options?: Partial<Options<LogoutData>>) => {
    const mutationOptions: UseMutationOptions<LogoutResponse, AxiosError<LogoutError>, Options<LogoutData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await LoginService.logout({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const recoverPasswordQueryKey = (options: Options<RecoverPasswordData>) => createQueryKey('recoverPassword', options);

export const recoverPasswordOptions = (options: Options<RecoverPasswordData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await LoginService.recoverPassword({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: recoverPasswordQueryKey(options)
    });
};

export const recoverPasswordMutation = (options?: Partial<Options<RecoverPasswordData>>) => {
    const mutationOptions: UseMutationOptions<RecoverPasswordResponse, AxiosError<RecoverPasswordError>, Options<RecoverPasswordData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await LoginService.recoverPassword({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const resetPasswordQueryKey = (options: Options<ResetPasswordData>) => createQueryKey('resetPassword', options);

export const resetPasswordOptions = (options: Options<ResetPasswordData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await LoginService.resetPassword({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: resetPasswordQueryKey(options)
    });
};

export const resetPasswordMutation = (options?: Partial<Options<ResetPasswordData>>) => {
    const mutationOptions: UseMutationOptions<ResetPasswordResponse, AxiosError<ResetPasswordError>, Options<ResetPasswordData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await LoginService.resetPassword({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUsersQueryKey = (options?: Options<GetUsersData>) => createQueryKey('getUsers', options);

export const getUsersOptions = (options?: Options<GetUsersData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await UsersService.getUsers({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUsersQueryKey(options)
    });
};

export const createUserQueryKey = (options: Options<CreateUserData>) => createQueryKey('createUser', options);

export const createUserOptions = (options: Options<CreateUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await UsersService.createUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: createUserQueryKey(options)
    });
};

export const createUserMutation = (options?: Partial<Options<CreateUserData>>) => {
    const mutationOptions: UseMutationOptions<CreateUserResponse, AxiosError<CreateUserError>, Options<CreateUserData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await UsersService.createUser({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const registerUserQueryKey = (options: Options<RegisterUserData>) => createQueryKey('registerUser', options);

export const registerUserOptions = (options: Options<RegisterUserData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await UsersService.registerUser({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: registerUserQueryKey(options)
    });
};

export const registerUserMutation = (options?: Partial<Options<RegisterUserData>>) => {
    const mutationOptions: UseMutationOptions<RegisterUserResponse, AxiosError<RegisterUserError>, Options<RegisterUserData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await UsersService.registerUser({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteUserMeMutation = (options?: Partial<Options<DeleteUserMeData>>) => {
    const mutationOptions: UseMutationOptions<DeleteUserMeResponse, AxiosError<DefaultError>, Options<DeleteUserMeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await UsersService.deleteUserMe({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserMeQueryKey = (options?: Options<GetUserMeData>) => createQueryKey('getUserMe', options);

export const getUserMeOptions = (options?: Options<GetUserMeData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await UsersService.getUserMe({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserMeQueryKey(options)
    });
};

export const updateUserMeMutation = (options?: Partial<Options<UpdateUserMeData>>) => {
    const mutationOptions: UseMutationOptions<UpdateUserMeResponse, AxiosError<UpdateUserMeError>, Options<UpdateUserMeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await UsersService.updateUserMe({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const updatePasswordMeMutation = (options?: Partial<Options<UpdatePasswordMeData>>) => {
    const mutationOptions: UseMutationOptions<UpdatePasswordMeResponse, AxiosError<UpdatePasswordMeError>, Options<UpdatePasswordMeData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await UsersService.updatePasswordMe({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const deleteUserByIdMutation = (options?: Partial<Options<DeleteUserByIdData>>) => {
    const mutationOptions: UseMutationOptions<DeleteUserByIdResponse, AxiosError<DeleteUserByIdError>, Options<DeleteUserByIdData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await UsersService.deleteUserById({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};

export const getUserByIdQueryKey = (options: Options<GetUserByIdData>) => createQueryKey('getUserById', options);

export const getUserByIdOptions = (options: Options<GetUserByIdData>) => {
    return queryOptions({
        queryFn: async ({ queryKey, signal }) => {
            const { data } = await UsersService.getUserById({
                ...options,
                ...queryKey[0],
                signal,
                throwOnError: true
            });
            return data;
        },
        queryKey: getUserByIdQueryKey(options)
    });
};

export const updateUserByIdMutation = (options?: Partial<Options<UpdateUserByIdData>>) => {
    const mutationOptions: UseMutationOptions<UpdateUserByIdResponse, AxiosError<UpdateUserByIdError>, Options<UpdateUserByIdData>> = {
        mutationFn: async (localOptions) => {
            const { data } = await UsersService.updateUserById({
                ...options,
                ...localOptions,
                throwOnError: true
            });
            return data;
        }
    };
    return mutationOptions;
};