// This file is auto-generated by @hey-api/openapi-ts

import { type Options as ClientOptions, type TDataShape, type Client, urlSearchParamsBodySerializer } from '@hey-api/client-axios';
import type { GetHealthData, GetHealthResponse, LoginData, LoginResponse, LoginError, RefreshData, RefreshResponse, RefreshError, LogoutData, LogoutResponse, LogoutError, RecoverPasswordData, RecoverPasswordResponse, RecoverPasswordError, ResetPasswordData, ResetPasswordResponse, ResetPasswordError, GetUsersData, GetUsersResponse, GetUsersError, CreateUserData, CreateUserResponse, CreateUserError, RegisterUserData, RegisterUserResponse, RegisterUserError, DeleteUserMeData, DeleteUserMeResponse, GetUserMeData, GetUserMeResponse, UpdateUserMeData, UpdateUserMeResponse, UpdateUserMeError, UpdatePasswordMeData, UpdatePasswordMeResponse, UpdatePasswordMeError, DeleteUserByIdData, DeleteUserByIdResponse, DeleteUserByIdError, GetUserByIdData, GetUserByIdResponse, GetUserByIdError, UpdateUserByIdData, UpdateUserByIdResponse, UpdateUserByIdError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class HealthService {
    /**
     * Get Health
     */
    public static getHealth<ThrowOnError extends boolean = true>(options?: Options<GetHealthData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetHealthResponse, unknown, ThrowOnError>({
            url: '/api/v1/health',
            ...options
        });
    }
    
}

export class LoginService {
    /**
     * Login
     */
    public static login<ThrowOnError extends boolean = true>(options: Options<LoginData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LoginResponse, LoginError, ThrowOnError>({
            ...urlSearchParamsBodySerializer,
            url: '/api/v1/login',
            ...options,
            headers: {
                'Content-Type': 'application/x-www-form-urlencoded',
                ...options?.headers
            }
        });
    }
    
    /**
     * Refresh
     */
    public static refresh<ThrowOnError extends boolean = true>(options: Options<RefreshData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<RefreshResponse, RefreshError, ThrowOnError>({
            url: '/api/v1/refresh',
            ...options
        });
    }
    
    /**
     * Logout
     */
    public static logout<ThrowOnError extends boolean = true>(options: Options<LogoutData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<LogoutResponse, LogoutError, ThrowOnError>({
            url: '/api/v1/logout',
            ...options
        });
    }
    
    /**
     * Recover Password
     */
    public static recoverPassword<ThrowOnError extends boolean = true>(options: Options<RecoverPasswordData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<RecoverPasswordResponse, RecoverPasswordError, ThrowOnError>({
            url: '/api/v1/password-recovery/{email}',
            ...options
        });
    }
    
    /**
     * Reset Password
     */
    public static resetPassword<ThrowOnError extends boolean = true>(options: Options<ResetPasswordData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<ResetPasswordResponse, ResetPasswordError, ThrowOnError>({
            url: '/api/v1/reset-password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}

export class UsersService {
    /**
     * Get Users
     */
    public static getUsers<ThrowOnError extends boolean = true>(options?: Options<GetUsersData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUsersResponse, GetUsersError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/',
            ...options
        });
    }
    
    /**
     * Create User
     */
    public static createUser<ThrowOnError extends boolean = true>(options: Options<CreateUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<CreateUserResponse, CreateUserError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Register User
     */
    public static registerUser<ThrowOnError extends boolean = true>(options: Options<RegisterUserData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).post<RegisterUserResponse, RegisterUserError, ThrowOnError>({
            url: '/api/v1/users/signup',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete User Me
     */
    public static deleteUserMe<ThrowOnError extends boolean = true>(options?: Options<DeleteUserMeData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).delete<DeleteUserMeResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Get User Me
     */
    public static getUserMe<ThrowOnError extends boolean = true>(options?: Options<GetUserMeData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUserMeResponse, unknown, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options
        });
    }
    
    /**
     * Update User Me
     */
    public static updateUserMe<ThrowOnError extends boolean = true>(options: Options<UpdateUserMeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<UpdateUserMeResponse, UpdateUserMeError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Update Password Me
     */
    public static updatePasswordMe<ThrowOnError extends boolean = true>(options: Options<UpdatePasswordMeData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<UpdatePasswordMeResponse, UpdatePasswordMeError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/me/password',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
    /**
     * Delete User By Id
     */
    public static deleteUserById<ThrowOnError extends boolean = true>(options: Options<DeleteUserByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).delete<DeleteUserByIdResponse, DeleteUserByIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Get User By Id
     */
    public static getUserById<ThrowOnError extends boolean = true>(options: Options<GetUserByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).get<GetUserByIdResponse, GetUserByIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options
        });
    }
    
    /**
     * Update User By Id
     */
    public static updateUserById<ThrowOnError extends boolean = true>(options: Options<UpdateUserByIdData, ThrowOnError>) {
        return (options.client ?? _heyApiClient).patch<UpdateUserByIdResponse, UpdateUserByIdError, ThrowOnError>({
            security: [
                {
                    scheme: 'bearer',
                    type: 'http'
                }
            ],
            url: '/api/v1/users/{user_id}',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}