// This file is auto-generated by @hey-api/openapi-ts

export type HttpValidationError = {
    detail?: Array<ValidationError>;
};

export type HealthRsp = {
    is_healthy: boolean;
};

export type Message = {
    msg: string;
};

export type PasswordReset = {
    token: string;
    new_password: string;
};

export type Tokens = {
    access_token: string;
    token_type?: string;
    refresh_token: string;
};

export type UserCreate = {
    is_active?: boolean;
    email: string;
    user_group?: string;
    password: string;
};

export type UserPublic = {
    is_active?: boolean;
    email: string;
    user_group?: string;
    id: string;
    created: string;
    updated: string;
};

export type UserRegister = {
    email: string;
    password: string;
};

export type UserUpdate = {
    is_active?: boolean;
    email?: string | null;
    user_group?: string;
    password?: string | null;
};

export type UserUpdateMe = {
    email?: string | null;
};

export type UserUpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UsersPublic = {
    users: Array<UserPublic>;
};

export type ValidationError = {
    loc: Array<string | number>;
    msg: string;
    type: string;
};

export type BodyLogin = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type GetHealthData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/health';
};

export type GetHealthResponses = {
    /**
     * Successful Response
     */
    200: HealthRsp;
};

export type GetHealthResponse = GetHealthResponses[keyof GetHealthResponses];

export type LoginData = {
    body: BodyLogin;
    path?: never;
    query?: never;
    url: '/api/v1/login';
};

export type LoginErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * Successful Response
     */
    200: Tokens;
};

export type LoginResponse = LoginResponses[keyof LoginResponses];

export type RefreshData = {
    body?: never;
    headers: {
        'x-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/refresh';
};

export type RefreshErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RefreshError = RefreshErrors[keyof RefreshErrors];

export type RefreshResponses = {
    /**
     * Successful Response
     */
    200: Tokens;
};

export type RefreshResponse = RefreshResponses[keyof RefreshResponses];

export type LogoutData = {
    body?: never;
    headers: {
        'x-token': string;
    };
    path?: never;
    query?: never;
    url: '/api/v1/logout';
};

export type LogoutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogoutError = LogoutErrors[keyof LogoutErrors];

export type LogoutResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LogoutResponse = LogoutResponses[keyof LogoutResponses];

export type RecoverPasswordData = {
    body?: never;
    path: {
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type RecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RecoverPasswordError = RecoverPasswordErrors[keyof RecoverPasswordErrors];

export type RecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type RecoverPasswordResponse = RecoverPasswordResponses[keyof RecoverPasswordResponses];

export type ResetPasswordData = {
    body: PasswordReset;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password';
};

export type ResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetPasswordError = ResetPasswordErrors[keyof ResetPasswordErrors];

export type ResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type ResetPasswordResponse = ResetPasswordResponses[keyof ResetPasswordResponses];

export type GetUsersData = {
    body?: never;
    path?: never;
    query?: {
        skip?: number;
        limit?: number;
    };
    url: '/api/v1/users/';
};

export type GetUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUsersError = GetUsersErrors[keyof GetUsersErrors];

export type GetUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type GetUsersResponse = GetUsersResponses[keyof GetUsersResponses];

export type CreateUserData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/users/';
};

export type CreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateUserError = CreateUserErrors[keyof CreateUserErrors];

export type CreateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type CreateUserResponse = CreateUserResponses[keyof CreateUserResponses];

export type RegisterUserData = {
    body: UserRegister;
    path?: never;
    query?: never;
    url: '/api/v1/users/signup';
};

export type RegisterUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterUserError = RegisterUserErrors[keyof RegisterUserErrors];

export type RegisterUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type RegisterUserResponse = RegisterUserResponses[keyof RegisterUserResponses];

export type DeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserMeResponse = DeleteUserMeResponses[keyof DeleteUserMeResponses];

export type GetUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetUserMeResponse = GetUserMeResponses[keyof GetUserMeResponses];

export type UpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserMeError = UpdateUserMeErrors[keyof UpdateUserMeErrors];

export type UpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserMeResponse = UpdateUserMeResponses[keyof UpdateUserMeResponses];

export type UpdatePasswordMeData = {
    body: UserUpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePasswordMeError = UpdatePasswordMeErrors[keyof UpdatePasswordMeErrors];

export type UpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdatePasswordMeResponse = UpdatePasswordMeResponses[keyof UpdatePasswordMeResponses];

export type DeleteUserByIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteUserByIdError = DeleteUserByIdErrors[keyof DeleteUserByIdErrors];

export type DeleteUserByIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteUserByIdResponse = DeleteUserByIdResponses[keyof DeleteUserByIdResponses];

export type GetUserByIdData = {
    body?: never;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type GetUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetUserByIdError = GetUserByIdErrors[keyof GetUserByIdErrors];

export type GetUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetUserByIdResponse = GetUserByIdResponses[keyof GetUserByIdResponses];

export type UpdateUserByIdData = {
    body: UserUpdate;
    path: {
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UpdateUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateUserByIdError = UpdateUserByIdErrors[keyof UpdateUserByIdErrors];

export type UpdateUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UpdateUserByIdResponse = UpdateUserByIdResponses[keyof UpdateUserByIdResponses];

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};