/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as IndexImport } from './routes/index'
import { Route as AdminIndexImport } from './routes/admin/index'
import { Route as AdminAppRouteImport } from './routes/admin/_app/route'
import { Route as AdminAppDashboardImport } from './routes/admin/_app/dashboard'

// Create Virtual Routes

const AdminImport = createFileRoute('/admin')()

// Create/Update Routes

const AdminRoute = AdminImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AdminIndexRoute = AdminIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAppRouteRoute = AdminAppRouteImport.update({
  id: '/admin/_app',
  getParentRoute: () => AdminRoute,
} as any)

const AdminAppDashboardRoute = AdminAppDashboardImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminAppRouteRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminImport
      parentRoute: typeof rootRoute
    }
    '/admin/_app': {
      id: '/admin/_app'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminAppRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexImport
      parentRoute: typeof AdminImport
    }
    '/admin/_app/dashboard': {
      id: '/admin/_app/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminAppDashboardImport
      parentRoute: typeof AdminAppRouteImport
    }
  }
}

// Create and export the route tree

interface AdminAppRouteRouteChildren {
  AdminAppDashboardRoute: typeof AdminAppDashboardRoute
}

const AdminAppRouteRouteChildren: AdminAppRouteRouteChildren = {
  AdminAppDashboardRoute: AdminAppDashboardRoute,
}

const AdminAppRouteRouteWithChildren = AdminAppRouteRoute._addFileChildren(
  AdminAppRouteRouteChildren,
)

interface AdminRouteChildren {
  AdminAppRouteRoute: typeof AdminAppRouteRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAppRouteRoute: AdminAppRouteRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminAppRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAppDashboardRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminIndexRoute
  '/admin/dashboard': typeof AdminAppDashboardRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/_app': typeof AdminAppRouteRouteWithChildren
  '/admin/': typeof AdminIndexRoute
  '/admin/_app/dashboard': typeof AdminAppDashboardRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/admin' | '/admin/' | '/admin/dashboard'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/admin' | '/admin/dashboard'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/admin'
    | '/admin/_app'
    | '/admin/'
    | '/admin/_app/dashboard'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  AdminRoute: typeof AdminRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  AdminRoute: AdminRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/login",
        "/admin"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/admin": {
      "filePath": "admin/_app",
      "children": [
        "/admin/_app",
        "/admin/"
      ]
    },
    "/admin/_app": {
      "filePath": "admin/_app/route.tsx",
      "parent": "/admin",
      "children": [
        "/admin/_app/dashboard"
      ]
    },
    "/admin/": {
      "filePath": "admin/index.tsx",
      "parent": "/admin"
    },
    "/admin/_app/dashboard": {
      "filePath": "admin/_app/dashboard.tsx",
      "parent": "/admin/_app"
    }
  }
}
ROUTE_MANIFEST_END */
